### ISSUE TITLE
Inconsistant label array size

### ISSUE THREAD

**Issue by rjesud** [TheJacksonLaboratory/dask_relabeling#1]
Hi! Thanks for creating this tool! This fills a large need in my workflows. 

I am using the tool to parallelize cellpose on an 2-channel WSI. 

Interestingly, the label array does not match the XY dimensions of the input array. Any thoughts?

![image](https://github.com/TheJacksonLaboratory/dask_relabeling/assets/46010245/c90b246c-fa9a-4253-bc96-90a85083b36d)

**Comment by fercer** [comment]
Hi @rjesud , thanks for noticing this issue!

The reason why the output's shape differs from the input is because there is a padding added to the image to complete the chunk sizes. However, the padding is not removed after the process.

I will fix this issue so the output is of the same shape of the input. In the meantime you can just crop the output to the original shape.

**Comment by rjesud** [comment]
Ah makes sense. Glad it is an easy fix. 

I can confirm cropping solves the issue as a workaround. 

r
